insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (1, 595, 341, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 825);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (2, 990, null, 'Maecenas ut massa quis augue luctus tincidunt.', 21);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (3, 597, 705, 'Ut tellus.', 746);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (4, 198, null, 'Ut at dolor quis odio consequat varius.', 565);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (5, 296, null, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 114);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (6, 321, null, 'Fusce posuere felis sed lacus.', 764);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (7, 716, null, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 608);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (8, 143, null, 'Duis at velit eu est congue elementum.', 671);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (9, 799, 843, 'Suspendisse potenti.', 824);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (10, 989, 481, 'Nunc nisl.', 105);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (11, 824, null, 'In congue.', 99);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (12, 773, null, 'Aliquam sit amet diam in magna bibendum imperdiet.', 186);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (13, 533, 623, 'Nulla ut erat id mauris vulputate elementum.', 671);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (14, 784, 4, 'Nulla tempus.', 889);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (15, 33, null, 'Duis at velit eu est congue elementum.', 425);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (16, 810, null, 'Suspendisse accumsan tortor quis turpis.', 580);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (17, 369, null, 'In hac habitasse platea dictumst.', 580);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (18, 27, 915, 'Vivamus in felis eu sapien cursus vestibulum.', 134);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (19, 97, null, 'Nam tristique tortor eu pede.', 510);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (20, 337, null, 'Nulla facilisi.', 942);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (21, 461, 584, 'Curabitur in libero ut massa volutpat convallis.', 152);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (22, 1000, null, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 593);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (23, 361, null, 'Maecenas pulvinar lobortis est.', 859);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (24, 707, null, 'Fusce posuere felis sed lacus.', 544);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (25, 252, null, 'Nulla nisl.', 30);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (26, 292, null, 'Donec ut mauris eget massa tempor convallis.', 415);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (27, 495, 873, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 636);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (28, 484, null, 'Nunc nisl.', 499);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (29, 995, null, 'Morbi ut odio.', 466);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (30, 197, 177, 'Vivamus vestibulum sagittis sapien.', 112);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (31, 618, null, 'In eleifend quam a odio.', 271);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (32, 318, null, 'In hac habitasse platea dictumst.', 917);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (33, 514, null, 'Nullam varius.', 303);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (34, 628, null, 'Integer ac neque.', 824);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (35, 891, null, 'Cras in purus eu magna vulputate luctus.', 709);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (36, 637, 986, 'Nullam porttitor lacus at turpis.', 700);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (37, 158, 699, 'Praesent blandit.', 150);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (38, 549, 996, 'Suspendisse ornare consequat lectus.', 968);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (39, 660, 803, 'Mauris ullamcorper purus sit amet nulla.', 309);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (40, 801, null, 'In hac habitasse platea dictumst.', 52);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (41, 986, null, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 824);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (42, 843, null, 'Proin risus.', 60);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (43, 691, 987, 'Proin risus.', 36);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (44, 94, null, 'Morbi ut odio.', 410);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (45, 440, null, 'Praesent blandit.', 613);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (46, 178, 765, 'Nam nulla.', 965);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (47, 809, 610, 'Integer tincidunt ante vel ipsum.', 123);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (48, 810, 555, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 682);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (49, 19, null, 'In hac habitasse platea dictumst.', 142);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (50, 347, 212, 'Vestibulum rutrum rutrum neque.', 618);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (51, 771, 937, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 728);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (52, 441, 217, 'Quisque ut erat.', 809);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (53, 84, null, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 566);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (54, 574, null, 'Vestibulum rutrum rutrum neque.', 510);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (55, 320, null, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 954);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (56, 769, null, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 390);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (57, 551, 140, 'Mauris ullamcorper purus sit amet nulla.', 119);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (58, 777, null, 'Praesent lectus.', 122);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (59, 83, null, 'Aliquam quis turpis eget elit sodales scelerisque.', 441);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (60, 1000, null, 'Suspendisse potenti.', 739);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (61, 504, null, 'Praesent lectus.', 873);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (62, 14, 800, 'Vivamus vestibulum sagittis sapien.', 548);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (63, 339, 820, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 971);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (64, 184, 617, 'Aenean fermentum.', 763);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (65, 139, 49, 'In sagittis dui vel nisl.', 46);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (66, 703, 463, 'Morbi porttitor lorem id ligula.', 180);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (67, 843, 668, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 699);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (68, 943, 201, 'Phasellus in felis.', 866);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (69, 329, 389, 'Etiam justo.', 667);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (70, 641, 403, 'Donec dapibus.', 320);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (71, 664, null, 'Mauris sit amet eros.', 473);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (72, 375, 499, 'Morbi ut odio.', 315);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (73, 825, null, 'Integer ac leo.', 431);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (74, 144, 939, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 825);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (75, 431, null, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 814);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (76, 11, 7, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 722);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (77, 106, null, 'In hac habitasse platea dictumst.', 955);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (78, 836, null, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 915);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (79, 57, null, 'Nulla facilisi.', 739);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (80, 589, null, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 195);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (81, 396, null, 'Mauris lacinia sapien quis libero.', 226);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (82, 91, 633, 'Maecenas ut massa quis augue luctus tincidunt.', 58);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (83, 483, 824, 'Maecenas pulvinar lobortis est.', 931);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (84, 346, null, 'Nunc purus.', 48);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (85, 281, null, 'Aliquam quis turpis eget elit sodales scelerisque.', 734);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (86, 366, null, 'Etiam faucibus cursus urna.', 646);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (87, 797, null, 'Curabitur in libero ut massa volutpat convallis.', 396);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (88, 613, null, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 770);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (89, 109, null, 'Etiam justo.', 577);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (90, 264, 394, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 682);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (91, 172, null, 'Nam dui.', 50);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (92, 583, null, 'Nam tristique tortor eu pede.', 135);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (93, 289, 783, 'Etiam faucibus cursus urna.', 802);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (94, 770, null, 'Integer tincidunt ante vel ipsum.', 584);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (95, 585, 776, 'Nulla mollis molestie lorem.', 471);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (96, 950, null, 'Ut at dolor quis odio consequat varius.', 572);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (97, 828, 881, 'In hac habitasse platea dictumst.', 755);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (98, 717, 643, 'Morbi ut odio.', 220);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (99, 672, null, 'Aenean lectus.', 735);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (100, 201, 106, 'Duis consequat dui nec nisi volutpat eleifend.', 519);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (101, 1, 47, 'Aliquam quis turpis eget elit sodales scelerisque.', 135);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (102, 924, null, 'Suspendisse ornare consequat lectus.', 246);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (103, 101, 725, 'In quis justo.', 553);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (104, 909, null, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 83);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (105, 209, null, 'Curabitur in libero ut massa volutpat convallis.', 331);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (106, 81, null, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 256);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (107, 458, null, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 716);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (108, 715, null, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 109);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (109, 193, null, 'Morbi a ipsum.', 299);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (110, 572, null, 'Suspendisse potenti.', 149);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (111, 763, 978, 'Vestibulum rutrum rutrum neque.', 79);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (112, 834, 200, 'Nullam molestie nibh in lectus.', 418);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (113, 56, null, 'Aliquam non mauris.', 776);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (114, 711, null, 'Vivamus tortor.', 888);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (115, 667, null, 'Etiam vel augue.', 978);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (116, 683, 7, 'Duis bibendum.', 452);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (117, 504, null, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 842);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (118, 941, 681, 'Suspendisse accumsan tortor quis turpis.', 537);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (119, 605, null, 'Etiam pretium iaculis justo.', 258);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (120, 550, null, 'Nunc nisl.', 385);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (121, 336, null, 'In eleifend quam a odio.', 59);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (122, 859, null, 'Aenean lectus.', 515);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (123, 210, null, 'Nulla suscipit ligula in lacus.', 279);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (124, 667, 887, 'Integer ac leo.', 241);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (125, 39, null, 'Ut at dolor quis odio consequat varius.', 516);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (126, 37, null, 'Morbi a ipsum.', 295);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (127, 661, 720, 'Phasellus in felis.', 490);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (128, 645, 699, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 276);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (129, 12, null, 'Cras in purus eu magna vulputate luctus.', 477);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (130, 996, null, 'Integer ac leo.', 929);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (131, 369, 559, 'Donec vitae nisi.', 902);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (132, 35, null, 'Praesent blandit.', 850);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (133, 103, null, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 316);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (134, 504, 706, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 266);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (135, 325, 633, 'Nullam molestie nibh in lectus.', 950);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (136, 571, null, 'Aenean sit amet justo.', 304);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (137, 611, null, 'Morbi a ipsum.', 132);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (138, 743, 196, 'In congue.', 736);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (139, 473, 428, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 959);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (140, 435, 486, 'Nulla nisl.', 619);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (141, 442, 152, 'Quisque id justo sit amet sapien dignissim vestibulum.', 311);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (142, 722, null, 'Vivamus tortor.', 740);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (143, 36, null, 'Nulla tellus.', 769);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (144, 762, 307, 'Curabitur gravida nisi at nibh.', 265);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (145, 474, null, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 109);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (146, 235, 856, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 966);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (147, 468, 103, 'Sed accumsan felis.', 433);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (148, 728, 445, 'Integer ac neque.', 30);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (149, 879, 437, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 655);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (150, 110, null, 'Curabitur convallis.', 159);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (151, 133, null, 'Cras pellentesque volutpat dui.', 570);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (152, 523, null, 'In quis justo.', 208);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (153, 396, 765, 'Maecenas ut massa quis augue luctus tincidunt.', 197);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (154, 350, 229, 'Aliquam quis turpis eget elit sodales scelerisque.', 422);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (155, 650, null, 'Nullam varius.', 562);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (156, 376, 948, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 536);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (157, 862, 913, 'Vivamus vel nulla eget eros elementum pellentesque.', 774);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (158, 433, 935, 'Curabitur at ipsum ac tellus semper interdum.', 130);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (159, 354, 691, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 131);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (160, 754, null, 'Proin risus.', 695);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (161, 494, null, 'Phasellus id sapien in sapien iaculis congue.', 152);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (162, 224, null, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 992);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (163, 161, null, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 974);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (164, 352, null, 'Morbi non quam nec dui luctus rutrum.', 310);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (165, 961, null, 'Vivamus vel nulla eget eros elementum pellentesque.', 474);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (166, 855, 576, 'Morbi quis tortor id nulla ultrices aliquet.', 611);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (167, 70, 643, 'Morbi a ipsum.', 623);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (168, 749, null, 'Donec semper sapien a libero.', 83);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (169, 446, 734, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 280);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (170, 478, 456, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 34);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (171, 5, null, 'Donec quis orci eget orci vehicula condimentum.', 185);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (172, 379, 59, 'Nunc rhoncus dui vel sem.', 550);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (173, 675, null, 'Pellentesque viverra pede ac diam.', 460);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (174, 671, 741, 'Aenean fermentum.', 97);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (175, 236, 126, 'Integer non velit.', 469);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (176, 413, 810, 'Morbi non lectus.', 692);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (177, 379, 660, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 21);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (178, 526, 628, 'Curabitur convallis.', 294);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (179, 654, 99, 'In congue.', 633);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (180, 405, null, 'Duis ac nibh.', 310);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (181, 535, null, 'In hac habitasse platea dictumst.', 171);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (182, 499, null, 'Cras non velit nec nisi vulputate nonummy.', 275);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (183, 239, null, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 980);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (184, 553, null, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 778);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (185, 739, 239, 'Pellentesque eget nunc.', 235);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (186, 661, 42, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 844);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (187, 560, 875, 'Donec quis orci eget orci vehicula condimentum.', 79);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (188, 579, 123, 'Vestibulum sed magna at nunc commodo placerat.', 86);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (189, 436, null, 'Vivamus tortor.', 678);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (190, 313, null, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 769);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (191, 755, null, 'Ut tellus.', 347);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (192, 1000, null, 'Curabitur in libero ut massa volutpat convallis.', 144);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (193, 534, 715, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 549);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (194, 357, null, 'Pellentesque ultrices mattis odio.', 35);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (195, 497, null, 'Duis aliquam convallis nunc.', 651);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (196, 288, 821, 'Morbi a ipsum.', 689);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (197, 161, 573, 'Nunc purus.', 602);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (198, 298, null, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 81);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (199, 605, 704, 'Mauris ullamcorper purus sit amet nulla.', 217);
insert into comentario (comentario_id, usuario_id, usuario_respuesta_id, comentario, multimedia_id) values (200, 53, 785, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 111);
