insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (501, 'tortor', 'libero', 'felis fusce posuere', 'amet', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (502, 'at', 'ornare', 'ut nulla', 'erat', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (503, 'odio', 'orci', 'in sapien iaculis', 'montes', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (504, 'dis', 'ipsum', 'venenatis turpis', 'arcu', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (505, 'vulputate', 'ultrices', 'sed', 'suspendisse', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (506, 'platea', 'suscipit', 'ut blandit', 'est', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (507, 'sapien', 'urna', 'tincidunt eu felis', 'ultrices', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (508, 'nec', 'duis', 'eleifend', 'ultrices', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (509, 'ullamcorper', 'vitae', 'amet eros suspendisse', 'ac', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (510, 'nulla', 'quis', 'phasellus in', 'quam', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (511, 'tempor', 'turpis', 'at nunc commodo', 'nulla', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (512, 'ipsum', 'donec', 'congue risus semper', 'quam', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (513, 'nulla', 'sed', 'sodales scelerisque mauris', 'sem', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (514, 'velit', 'dui', 'dolor', 'luctus', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (515, 'id', 'elementum', 'ultrices', 'mattis', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (516, 'accumsan', 'in', 'nullam varius nulla', 'in', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (517, 'turpis', 'erat', 'suscipit nulla', 'vitae', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (518, 'felis', 'parturient', 'dapibus nulla suscipit', 'cras', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (519, 'ut', 'ipsum', 'tortor', 'tempor', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (520, 'pretium', 'curabitur', 'duis consequat', 'justo', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (521, 'at', 'ipsum', 'ornare imperdiet', 'vestibulum', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (522, 'fermentum', 'sollicitudin', 'sapien arcu', 'quis', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (523, 'turpis', 'leo', 'morbi', 'proin', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (524, 'lacus', 'gravida', 'eros elementum', 'primis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (525, 'duis', 'vitae', 'nisl duis', 'id', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (526, 'scelerisque', 'nibh', 'amet', 'sem', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (527, 'primis', 'curabitur', 'habitasse platea dictumst', 'ut', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (528, 'maecenas', 'in', 'donec quis', 'feugiat', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (529, 'viverra', 'sapien', 'posuere', 'arcu', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (530, 'interdum', 'amet', 'ultrices posuere', 'posuere', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (531, 'turpis', 'cubilia', 'ut', 'dictumst', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (532, 'orci', 'sagittis', 'euismod', 'quis', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (533, 'ac', 'augue', 'luctus', 'volutpat', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (534, 'vestibulum', 'ac', 'at velit eu', 'venenatis', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (535, 'volutpat', 'cursus', 'sagittis sapien cum', 'lectus', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (536, 'felis', 'platea', 'rutrum at', 'gravida', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (537, 'purus', 'nunc', 'arcu adipiscing', 'sapien', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (538, 'pede', 'ut', 'tempus semper', 'vehicula', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (539, 'condimentum', 'sollicitudin', 'neque duis bibendum', 'pellentesque', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (540, 'metus', 'elementum', 'mauris laoreet ut', 'augue', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (541, 'sem', 'pharetra', 'posuere metus vitae', 'a', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (542, 'hac', 'in', 'justo eu massa', 'donec', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (543, 'amet', 'aliquam', 'consequat metus', 'donec', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (544, 'vivamus', 'turpis', 'ante nulla', 'pellentesque', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (545, 'ut', 'ultrices', 'id lobortis convallis', 'etiam', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (546, 'in', 'iaculis', 'dui luctus rutrum', 'quam', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (547, 'viverra', 'integer', 'at', 'in', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (548, 'morbi', 'faucibus', 'ipsum dolor sit', 'nisl', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (549, 'pellentesque', 'duis', 'nullam', 'venenatis', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (550, 'ut', 'suspendisse', 'aenean fermentum', 'at', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (551, 'eu', 'integer', 'at nulla suspendisse', 'ac', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (552, 'risus', 'pede', 'sapien dignissim', 'duis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (553, 'tortor', 'id', 'nulla', 'amet', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (554, 'morbi', 'commodo', 'et ultrices posuere', 'cubilia', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (555, 'faucibus', 'iaculis', 'morbi vel lectus', 'a', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (556, 'proin', 'lorem', 'in consequat ut', 'amet', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (557, 'posuere', 'montes', 'porta volutpat', 'nunc', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (558, 'eros', 'rhoncus', 'eget', 'consectetuer', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (559, 'iaculis', 'vel', 'praesent blandit', 'eros', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (560, 'morbi', 'tempus', 'hendrerit at vulputate', 'potenti', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (561, 'quam', 'turpis', 'cum sociis', 'massa', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (562, 'magna', 'ultrices', 'eget congue', 'proin', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (563, 'ornare', 'mattis', 'donec posuere metus', 'dapibus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (564, 'in', 'eget', 'aenean lectus', 'ante', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (565, 'luctus', 'quis', 'cursus id turpis', 'ipsum', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (566, 'ipsum', 'aenean', 'sit amet', 'pretium', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (567, 'nullam', 'neque', 'sit amet nunc', 'nec', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (568, 'amet', 'posuere', 'potenti in eleifend', 'quis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (569, 'etiam', 'lacinia', 'eleifend luctus ultricies', 'elementum', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (570, 'lorem', 'sollicitudin', 'quis', 'bibendum', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (571, 'pharetra', 'venenatis', 'dolor sit amet', 'interdum', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (572, 'purus', 'faucibus', 'cras non', 'vel', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (573, 'in', 'ipsum', 'quam', 'adipiscing', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (574, 'in', 'eget', 'nec molestie', 'feugiat', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (575, 'sollicitudin', 'massa', 'ultrices posuere cubilia', 'dolor', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (576, 'nulla', 'iaculis', 'pede', 'donec', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (577, 'rutrum', 'amet', 'non', 'consequat', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (578, 'nam', 'lacinia', 'varius nulla facilisi', 'vestibulum', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (579, 'id', 'mauris', 'sapien in', 'aliquam', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (580, 'fusce', 'ut', 'nulla neque libero', 'porttitor', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (581, 'mauris', 'feugiat', 'in faucibus', 'donec', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (582, 'erat', 'posuere', 'morbi', 'vel', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (583, 'rutrum', 'vulputate', 'porta', 'ipsum', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (584, 'id', 'duis', 'massa quis augue', 'blandit', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (585, 'mattis', 'ullamcorper', 'ante nulla', 'adipiscing', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (586, 'eget', 'auctor', 'hac', 'aliquet', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (587, 'hac', 'nisi', 'semper', 'in', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (588, 'non', 'sem', 'aliquam convallis nunc', 'laoreet', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (589, 'lobortis', 'commodo', 'vulputate justo', 'orci', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (590, 'venenatis', 'eros', 'posuere cubilia', 'congue', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (591, 'nulla', 'venenatis', 'amet sapien', 'id', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (592, 'dolor', 'non', 'leo maecenas', 'magna', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (593, 'nibh', 'rhoncus', 'quam nec', 'suspendisse', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (594, 'vitae', 'vel', 'vestibulum aliquet', 'nulla', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (595, 'dui', 'erat', 'justo aliquam', 'luctus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (596, 'sed', 'at', 'parturient', 'dictumst', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (597, 'vestibulum', 'donec', 'donec dapibus', 'eros', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (598, 'praesent', 'justo', 'condimentum curabitur', 'nec', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (599, 'cum', 'velit', 'a ipsum integer', 'nec', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (600, 'odio', 'tellus', 'at', 'praesent', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (601, 'velit', 'ipsum', 'non velit', 'velit', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (602, 'turpis', 'felis', 'magna', 'erat', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (603, 'ipsum', 'id', 'dignissim vestibulum vestibulum', 'fringilla', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (604, 'vestibulum', 'mauris', 'semper interdum', 'enim', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (605, 'lobortis', 'nulla', 'ipsum primis', 'tincidunt', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (606, 'sapien', 'commodo', 'non', 'ultricies', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (607, 'libero', 'a', 'auctor gravida', 'sed', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (608, 'hac', 'quisque', 'dolor morbi vel', 'pede', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (609, 'amet', 'vel', 'iaculis', 'nulla', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (610, 'viverra', 'sem', 'risus', 'amet', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (611, 'odio', 'vel', 'tincidunt lacus', 'nullam', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (612, 'metus', 'integer', 'eget nunc donec', 'erat', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (613, 'sociis', 'dapibus', 'morbi a', 'ac', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (614, 'etiam', 'etiam', 'suspendisse', 'augue', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (615, 'faucibus', 'eget', 'lorem', 'cras', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (616, 'donec', 'vestibulum', 'est donec', 'eu', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (617, 'fringilla', 'sit', 'quis orci eget', 'tempor', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (618, 'leo', 'suscipit', 'penatibus et', 'sodales', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (619, 'lacus', 'accumsan', 'odio donec vitae', 'justo', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (620, 'pede', 'pretium', 'ultrices libero non', 'et', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (621, 'purus', 'quis', 'erat quisque erat', 'rutrum', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (622, 'sed', 'ante', 'proin at', 'sit', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (623, 'adipiscing', 'vestibulum', 'sit amet nulla', 'habitasse', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (624, 'ullamcorper', 'vestibulum', 'dolor vel', 'sollicitudin', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (625, 'porttitor', 'augue', 'ipsum primis', 'ante', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (626, 'in', 'dictumst', 'rhoncus dui vel', 'vel', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (627, 'amet', 'vulputate', 'natoque penatibus', 'at', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (628, 'ultricies', 'praesent', 'platea', 'vivamus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (629, 'lacinia', 'hac', 'est', 'suspendisse', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (630, 'fringilla', 'quam', 'nulla', 'libero', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (631, 'at', 'ut', 'sollicitudin vitae', 'ipsum', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (632, 'ante', 'volutpat', 'nullam sit', 'luctus', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (633, 'at', 'at', 'leo rhoncus', 'morbi', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (634, 'habitasse', 'sollicitudin', 'lacus morbi sem', 'ligula', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (635, 'consectetuer', 'aenean', 'neque aenean auctor', 'mauris', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (636, 'vestibulum', 'nullam', 'curabitur convallis', 'at', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (637, 'donec', 'tortor', 'dapibus', 'consequat', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (638, 'vestibulum', 'dictumst', 'nulla', 'vitae', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (639, 'at', 'orci', 'cum sociis', 'dui', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (640, 'aenean', 'tristique', 'curabitur at ipsum', 'ante', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (641, 'donec', 'sapien', 'nulla', 'sed', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (642, 'lorem', 'massa', 'justo morbi', 'ultrices', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (643, 'vulputate', 'justo', 'id lobortis convallis', 'sem', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (644, 'varius', 'hac', 'vestibulum rutrum', 'ligula', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (645, 'a', 'dapibus', 'tortor sollicitudin', 'a', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (646, 'erat', 'posuere', 'lobortis vel', 'curae', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (647, 'a', 'arcu', 'praesent', 'justo', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (648, 'at', 'sit', 'nulla elit', 'lectus', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (649, 'in', 'felis', 'metus aenean', 'morbi', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (650, 'faucibus', 'sed', 'nunc', 'ultrices', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (651, 'maecenas', 'eu', 'arcu libero rutrum', 'donec', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (652, 'porttitor', 'venenatis', 'at', 'montes', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (653, 'ac', 'lectus', 'rutrum neque aenean', 'non', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (654, 'pulvinar', 'etiam', 'nullam', 'sed', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (655, 'velit', 'vivamus', 'consequat', 'pretium', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (656, 'ut', 'faucibus', 'vehicula consequat', 'nisl', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (657, 'primis', 'sagittis', 'nullam porttitor', 'convallis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (658, 'ipsum', 'consequat', 'semper', 'justo', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (659, 'congue', 'id', 'tempus vivamus in', 'integer', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (660, 'velit', 'leo', 'leo maecenas', 'vel', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (661, 'adipiscing', 'massa', 'interdum venenatis', 'nunc', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (662, 'faucibus', 'pede', 'erat volutpat in', 'integer', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (663, 'consequat', 'elementum', 'nibh fusce', 'est', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (664, 'adipiscing', 'ligula', 'neque vestibulum eget', 'vestibulum', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (665, 'in', 'ante', 'luctus cum', 'donec', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (666, 'aliquet', 'morbi', 'ut', 'ultrices', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (667, 'eros', 'eget', 'habitasse platea dictumst', 'feugiat', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (668, 'in', 'nisl', 'in sapien', 'nulla', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (669, 'nulla', 'in', 'duis', 'consequat', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (670, 'erat', 'praesent', 'nec euismod', 'massa', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (671, 'primis', 'vivamus', 'quis turpis', 'quis', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (672, 'semper', 'quam', 'cursus urna', 'vitae', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (673, 'magna', 'nulla', 'vel', 'vel', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (674, 'risus', 'vel', 'in libero', 'faucibus', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (675, 'morbi', 'nulla', 'volutpat quam', 'ridiculus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (676, 'pulvinar', 'justo', 'in tempor', 'sodales', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (677, 'dapibus', 'volutpat', 'velit eu', 'sit', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (678, 'faucibus', 'sem', 'ultrices posuere cubilia', 'congue', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (679, 'ultrices', 'turpis', 'vehicula condimentum', 'dignissim', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (680, 'ipsum', 'ridiculus', 'neque', 'ligula', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (681, 'ultrices', 'quam', 'id lobortis', 'faucibus', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (682, 'viverra', 'morbi', 'ipsum', 'et', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (683, 'mattis', 'ultrices', 'erat', 'vulputate', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (684, 'mattis', 'ac', 'in hac habitasse', 'luctus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (685, 'ultrices', 'in', 'proin risus', 'molestie', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (686, 'dui', 'tortor', 'a odio in', 'sapien', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (687, 'dui', 'nulla', 'ultrices vel augue', 'erat', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (688, 'non', 'eget', 'nulla ac', 'lectus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (689, 'in', 'vestibulum', 'venenatis', 'varius', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (690, 'nec', 'quis', 'consequat nulla nisl', 'sodales', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (691, 'lorem', 'sapien', 'odio', 'quis', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (692, 'elementum', 'semper', 'magna at nunc', 'eu', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (693, 'luctus', 'lectus', 'amet', 'in', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (694, 'congue', 'donec', 'consectetuer adipiscing', 'ipsum', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (695, 'integer', 'quis', 'est phasellus', 'donec', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (696, 'ultrices', 'integer', 'platea', 'arcu', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (697, 'nunc', 'lacus', 'dui proin leo', 'sed', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (698, 'id', 'sem', 'ultrices posuere cubilia', 'a', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (699, 'sem', 'ac', 'bibendum imperdiet', 'rutrum', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (700, 'odio', 'parturient', 'justo nec condimentum', 'vestibulum', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (701, 'hendrerit', 'orci', 'tristique tortor eu', 'nulla', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (702, 'in', 'cubilia', 'sapien sapien non', 'cubilia', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (703, 'id', 'malesuada', 'sit amet', 'nonummy', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (704, 'tincidunt', 'vel', 'vivamus', 'mi', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (705, 'in', 'eros', 'fusce lacus', 'in', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (706, 'duis', 'ante', 'mi', 'sit', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (707, 'adipiscing', 'natoque', 'tristique tortor eu', 'pretium', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (708, 'cursus', 'varius', 'congue eget', 'lorem', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (709, 'vulputate', 'vivamus', 'donec', 'posuere', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (710, 'turpis', 'quis', 'natoque', 'sapien', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (711, 'at', 'elementum', 'ultrices posuere cubilia', 'justo', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (712, 'nisl', 'lacus', 'eros', 'morbi', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (713, 'aliquam', 'venenatis', 'eget nunc', 'sit', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (714, 'lacus', 'augue', 'pede morbi porttitor', 'varius', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (715, 'sem', 'odio', 'dapibus', 'pede', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (716, 'quisque', 'faucibus', 'orci pede', 'ultrices', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (717, 'id', 'in', 'enim blandit mi', 'montes', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (718, 'quis', 'lectus', 'quam turpis adipiscing', 'ultricies', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (719, 'nam', 'nec', 'platea', 'mattis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (720, 'ultrices', 'mauris', 'proin', 'semper', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (721, 'maecenas', 'nunc', 'eleifend quam a', 'penatibus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (722, 'nulla', 'maecenas', 'massa id lobortis', 'ac', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (723, 'tincidunt', 'nullam', 'erat nulla tempus', 'posuere', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (724, 'est', 'et', 'dis parturient montes', 'imperdiet', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (725, 'vitae', 'vestibulum', 'et tempus semper', 'tincidunt', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (726, 'ut', 'sit', 'quis orci', 'at', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (727, 'nam', 'ac', 'imperdiet', 'in', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (728, 'eget', 'pellentesque', 'quam', 'ultricies', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (729, 'ante', 'maecenas', 'amet lobortis sapien', 'quam', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (730, 'sed', 'faucibus', 'morbi', 'ridiculus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (731, 'sed', 'lorem', 'orci', 'odio', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (732, 'donec', 'et', 'fusce consequat', 'suscipit', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (733, 'ac', 'donec', 'vestibulum', 'morbi', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (734, 'tortor', 'in', 'dapibus nulla', 'ut', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (735, 'tellus', 'ipsum', 'purus', 'sit', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (736, 'luctus', 'vel', 'blandit nam', 'augue', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (737, 'augue', 'non', 'lorem ipsum dolor', 'in', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (738, 'molestie', 'quis', 'volutpat eleifend donec', 'aliquet', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (739, 'luctus', 'dis', 'morbi vestibulum', 'nec', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (740, 'lacus', 'ac', 'aenean', 'rhoncus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (741, 'aliquet', 'enim', 'lacus', 'metus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (742, 'pede', 'pellentesque', 'sagittis nam congue', 'rhoncus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (743, 'quisque', 'interdum', 'vestibulum', 'odio', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (744, 'orci', 'sapien', 'ut blandit', 'ultrices', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (745, 'nec', 'pretium', 'et', 'ipsum', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (746, 'sagittis', 'tincidunt', 'penatibus et magnis', 'ut', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (747, 'morbi', 'lacus', 'eget', 'vitae', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (748, 'odio', 'amet', 'porta volutpat erat', 'faucibus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (749, 'congue', 'in', 'lacus', 'sed', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (750, 'in', 'adipiscing', 'dapibus', 'curae', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (751, 'interdum', 'velit', 'sapien urna', 'commodo', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (752, 'vulputate', 'morbi', 'sed accumsan', 'rutrum', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (753, 'turpis', 'ac', 'nullam porttitor', 'habitasse', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (754, 'mauris', 'pulvinar', 'pretium iaculis', 'sapien', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (755, 'mauris', 'hac', 'quam', 'pede', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (756, 'aliquet', 'ut', 'cursus vestibulum proin', 'at', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (757, 'accumsan', 'molestie', 'at', 'enim', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (758, 'venenatis', 'quam', 'lorem ipsum', 'mi', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (759, 'amet', 'blandit', 'mauris sit amet', 'fermentum', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (760, 'cursus', 'eu', 'nec', 'nulla', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (761, 'erat', 'consequat', 'sit', 'primis', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (762, 'venenatis', 'at', 'orci', 'eu', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (763, 'faucibus', 'arcu', 'felis fusce', 'ridiculus', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (764, 'duis', 'erat', 'integer', 'lacinia', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (765, 'sem', 'eget', 'proin eu mi', 'etiam', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (766, 'quis', 'quis', 'amet diam in', 'posuere', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (767, 'orci', 'non', 'nunc rhoncus dui', 'ante', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (768, 'hac', 'justo', 'metus arcu adipiscing', 'vel', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (769, 'eu', 'nulla', 'lacinia aenean sit', 'praesent', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (770, 'non', 'luctus', 'integer tincidunt ante', 'nascetur', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (771, 'turpis', 'id', 'vestibulum vestibulum ante', 'nulla', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (772, 'nulla', 'nisl', 'odio', 'morbi', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (773, 'aliquet', 'neque', 'morbi porttitor lorem', 'ut', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (774, 'ut', 'nibh', 'metus', 'mi', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (775, 'integer', 'justo', 'adipiscing molestie', 'magna', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (776, 'vel', 'arcu', 'faucibus orci', 'curabitur', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (777, 'ullamcorper', 'at', 'platea dictumst', 'nulla', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (778, 'quam', 'in', 'aliquet at', 'quis', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (779, 'accumsan', 'nec', 'diam', 'sem', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (780, 'quam', 'quis', 'viverra', 'montes', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (781, 'erat', 'consequat', 'integer', 'primis', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (782, 'nunc', 'vitae', 'erat nulla tempus', 'ante', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (783, 'ac', 'sed', 'nibh in', 'est', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (784, 'nunc', 'amet', 'potenti in eleifend', 'elementum', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (785, 'erat', 'nulla', 'nulla suscipit', 'ipsum', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (786, 'duis', 'in', 'nulla', 'fusce', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (787, 'semper', 'dis', 'hac', 'accumsan', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (788, 'proin', 'in', 'in', 'sociis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (789, 'vestibulum', 'pellentesque', 'orci luctus et', 'auctor', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (790, 'volutpat', 'rutrum', 'tristique est', 'suscipit', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (791, 'eget', 'non', 'at velit', 'dui', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (792, 'non', 'amet', 'nisi', 'pede', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (793, 'phasellus', 'dolor', 'pede', 'luctus', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (794, 'ligula', 'rutrum', 'eget rutrum at', 'quis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (795, 'bibendum', 'ipsum', 'ligula pellentesque ultrices', 'augue', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (796, 'odio', 'ligula', 'ipsum primis', 'tincidunt', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (797, 'lectus', 'vestibulum', 'justo morbi ut', 'tristique', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (798, 'ut', 'eu', 'nulla neque', 'eros', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (799, 'gravida', 'hac', 'pellentesque', 'ligula', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (800, 'enim', 'quam', 'morbi sem', 'ac', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (801, 'gravida', 'maecenas', 'curabitur at', 'augue', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (802, 'dictumst', 'erat', 'nunc donec', 'ante', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (803, 'lorem', 'elit', 'justo maecenas', 'donec', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (804, 'gravida', 'leo', 'sed vestibulum sit', 'odio', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (805, 'varius', 'purus', 'diam', 'felis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (806, 'augue', 'duis', 'adipiscing', 'rhoncus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (807, 'platea', 'volutpat', 'ipsum praesent', 'quisque', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (808, 'amet', 'ultrices', 'in ante', 'quisque', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (809, 'nisi', 'rutrum', 'tempus', 'amet', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (810, 'et', 'dictumst', 'sociis natoque', 'congue', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (811, 'posuere', 'eget', 'semper interdum mauris', 'nulla', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (812, 'sit', 'lacus', 'volutpat', 'feugiat', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (813, 'sit', 'ac', 'non', 'phasellus', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (814, 'est', 'nisl', 'erat eros', 'nullam', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (815, 'nulla', 'nunc', 'feugiat non pretium', 'luctus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (816, 'ante', 'elementum', 'congue vivamus', 'tempor', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (817, 'penatibus', 'turpis', 'viverra eget congue', 'ac', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (818, 'eu', 'nec', 'quam', 'in', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (819, 'ipsum', 'mattis', 'neque sapien', 'nibh', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (820, 'placerat', 'duis', 'mus vivamus vestibulum', 'turpis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (821, 'sit', 'ut', 'nam ultrices libero', 'odio', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (822, 'nulla', 'maecenas', 'massa', 'nec', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (823, 'tristique', 'nibh', 'lectus pellentesque eget', 'felis', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (824, 'tempor', 'eleifend', 'cursus vestibulum', 'nunc', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (825, 'vestibulum', 'platea', 'justo etiam pretium', 'iaculis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (826, 'nisi', 'hac', 'hac habitasse', 'neque', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (827, 'sed', 'vel', 'ultrices erat', 'porttitor', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (828, 'sit', 'rhoncus', 'nonummy integer', 'congue', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (829, 'vitae', 'eu', 'eleifend quam', 'id', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (830, 'eleifend', 'at', 'vel est donec', 'rhoncus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (831, 'risus', 'donec', 'in lacus curabitur', 'ligula', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (832, 'maecenas', 'vel', 'mi nulla ac', 'in', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (833, 'in', 'eleifend', 'porttitor lorem', 'amet', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (834, 'donec', 'imperdiet', 'nonummy', 'nunc', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (835, 'volutpat', 'luctus', 'in faucibus orci', 'molestie', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (836, 'morbi', 'eget', 'eget congue', 'lobortis', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (837, 'interdum', 'in', 'cubilia curae', 'in', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (838, 'condimentum', 'velit', 'ut', 'in', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (839, 'viverra', 'consequat', 'metus', 'interdum', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (840, 'est', 'praesent', 'ligula suspendisse ornare', 'duis', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (841, 'rutrum', 'ipsum', 'non mattis', 'sapien', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (842, 'quis', 'vestibulum', 'aenean', 'elit', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (843, 'integer', 'mauris', 'sed interdum', 'congue', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (844, 'fusce', 'consectetuer', 'malesuada in', 'metus', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (845, 'lacinia', 'integer', 'odio', 'eleifend', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (846, 'turpis', 'sit', 'mi nulla', 'ultrices', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (847, 'metus', 'risus', 'ipsum primis in', 'amet', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (848, 'lacinia', 'mauris', 'vel', 'nulla', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (849, 'sapien', 'ut', 'curae', 'mattis', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (850, 'mus', 'enim', 'in faucibus', 'at', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (851, 'sed', 'aenean', 'ultrices posuere', 'convallis', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (852, 'tincidunt', 'consectetuer', 'sit', 'turpis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (853, 'penatibus', 'ante', 'leo odio condimentum', 'ante', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (854, 'quis', 'at', 'in porttitor pede', 'non', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (855, 'suspendisse', 'velit', 'lectus in', 'congue', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (856, 'non', 'nulla', 'mauris lacinia sapien', 'orci', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (857, 'fermentum', 'semper', 'ut', 'tristique', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (858, 'odio', 'semper', 'elit proin', 'vel', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (859, 'habitasse', 'in', 'nulla nisl', 'luctus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (860, 'mauris', 'mauris', 'posuere cubilia', 'cubilia', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (861, 'sit', 'pede', 'lorem ipsum dolor', 'lobortis', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (862, 'in', 'duis', 'ipsum ac tellus', 'volutpat', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (863, 'rutrum', 'non', 'nam ultrices libero', 'sapien', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (864, 'ac', 'lacus', 'risus auctor', 'tempus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (865, 'vivamus', 'nulla', 'duis', 'eu', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (866, 'cum', 'pellentesque', 'in felis', 'turpis', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (867, 'amet', 'sapien', 'ultrices', 'purus', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (868, 'sit', 'faucibus', 'curae donec pharetra', 'faucibus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (869, 'parturient', 'potenti', 'turpis a', 'cursus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (870, 'morbi', 'aliquam', 'luctus ultricies', 'morbi', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (871, 'pede', 'pretium', 'ultrices', 'pulvinar', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (872, 'nisi', 'dui', 'tortor duis mattis', 'ac', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (873, 'rutrum', 'massa', 'praesent lectus', 'nisi', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (874, 'enim', 'quam', 'erat', 'pede', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (875, 'sed', 'proin', 'suscipit', 'pede', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (876, 'non', 'pellentesque', 'felis', 'venenatis', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (877, 'ultrices', 'nulla', 'erat eros', 'scelerisque', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (878, 'habitasse', 'nulla', 'viverra pede', 'et', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (879, 'quam', 'aliquam', 'nulla', 'interdum', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (880, 'ridiculus', 'eget', 'vel lectus', 'odio', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (881, 'sed', 'ultrices', 'quam suspendisse', 'cubilia', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (882, 'habitasse', 'hac', 'iaculis justo', 'blandit', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (883, 'vel', 'nunc', 'tellus nisi eu', 'vulputate', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (884, 'non', 'placerat', 'nam tristique', 'rhoncus', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (885, 'in', 'justo', 'mi pede malesuada', 'volutpat', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (886, 'viverra', 'sed', 'dis parturient montes', 'vitae', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (887, 'nunc', 'mattis', 'posuere cubilia curae', 'iaculis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (888, 'mi', 'molestie', 'odio consequat', 'nisi', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (889, 'rhoncus', 'ut', 'quam turpis adipiscing', 'nec', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (890, 'lobortis', 'non', 'magna ac', 'neque', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (891, 'odio', 'a', 'cubilia curae duis', 'in', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (892, 'pellentesque', 'porta', 'penatibus et', 'suspendisse', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (893, 'leo', 'nunc', 'ipsum', 'nulla', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (894, 'sed', 'in', 'aenean lectus pellentesque', 'pede', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (895, 'elementum', 'posuere', 'proin', 'at', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (896, 'eget', 'enim', 'in', 'est', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (897, 'justo', 'at', 'ridiculus mus etiam', 'pede', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (898, 'pellentesque', 'in', 'volutpat', 'risus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (899, 'at', 'quis', 'adipiscing elit proin', 'mauris', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (900, 'dapibus', 'eget', 'auctor', 'eu', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (901, 'porta', 'justo', 'tortor quis', 'platea', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (902, 'morbi', 'nisi', 'congue', 'accumsan', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (903, 'magna', 'cursus', 'ipsum', 'justo', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (904, 'in', 'at', 'tincidunt lacus at', 'felis', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (905, 'mauris', 'metus', 'nunc proin', 'sapien', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (906, 'amet', 'natoque', 'consectetuer adipiscing', 'proin', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (907, 'non', 'viverra', 'ut suscipit a', 'id', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (908, 'massa', 'eleifend', 'at velit vivamus', 'lobortis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (909, 'parturient', 'ante', 'donec odio justo', 'tellus', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (910, 'massa', 'pede', 'potenti nullam porttitor', 'sapien', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (911, 'quam', 'turpis', 'id consequat', 'morbi', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (912, 'cubilia', 'sapien', 'felis donec semper', 'interdum', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (913, 'non', 'aliquam', 'nulla ac enim', 'elit', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (914, 'nam', 'cras', 'lectus pellentesque eget', 'turpis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (915, 'non', 'porttitor', 'et tempus semper', 'justo', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (916, 'vivamus', 'ligula', 'duis mattis egestas', 'arcu', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (917, 'platea', 'odio', 'venenatis non', 'augue', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (918, 'natoque', 'dis', 'augue vel accumsan', 'eros', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (919, 'purus', 'ipsum', 'eros elementum', 'mattis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (920, 'vulputate', 'interdum', 'sit amet lobortis', 'semper', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (921, 'proin', 'vel', 'augue', 'maecenas', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (922, 'et', 'sapien', 'vel ipsum praesent', 'consequat', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (923, 'et', 'ultricies', 'sit', 'enim', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (924, 'justo', 'justo', 'habitasse platea', 'in', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (925, 'elementum', 'felis', 'proin leo', 'consequat', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (926, 'justo', 'fermentum', 'proin', 'ultrices', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (927, 'congue', 'in', 'nam', 'blandit', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (928, 'vel', 'orci', 'interdum mauris ullamcorper', 'cras', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (929, 'rhoncus', 'est', 'sagittis dui vel', 'habitasse', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (930, 'vestibulum', 'rutrum', 'augue luctus', 'libero', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (931, 'erat', 'bibendum', 'nam nulla', 'malesuada', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (932, 'praesent', 'lacus', 'primis in faucibus', 'curabitur', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (933, 'orci', 'vestibulum', 'sem fusce', 'vestibulum', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (934, 'penatibus', 'ipsum', 'id', 'eget', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (935, 'ligula', 'ante', 'vestibulum', 'lorem', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (936, 'congue', 'ipsum', 'pretium iaculis diam', 'donec', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (937, 'eget', 'ridiculus', 'hac', 'mi', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (938, 'nisl', 'nisl', 'lorem ipsum', 'proin', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (939, 'ut', 'congue', 'suscipit', 'erat', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (940, 'at', 'amet', 'cras non velit', 'mi', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (941, 'quisque', 'aliquam', 'ultrices', 'vulputate', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (942, 'sollicitudin', 'maecenas', 'massa donec dapibus', 'curae', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (943, 'in', 'pede', 'odio porttitor', 'mi', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (944, 'justo', 'posuere', 'posuere cubilia', 'proin', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (945, 'adipiscing', 'accumsan', 'posuere cubilia curae', 'et', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (946, 'lobortis', 'volutpat', 'in sagittis', 'sed', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (947, 'eros', 'eu', 'vehicula consequat', 'nullam', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (948, 'libero', 'luctus', 'in magna bibendum', 'erat', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (949, 'purus', 'fusce', 'a libero nam', 'non', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (950, 'luctus', 'pede', 'vestibulum proin eu', 'tellus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (951, 'lectus', 'tincidunt', 'mauris lacinia', 'nibh', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (952, 'vulputate', 'nulla', 'cursus urna', 'consequat', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (953, 'euismod', 'morbi', 'elit ac', 'dui', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (954, 'aenean', 'nec', 'eros', 'accumsan', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (955, 'vulputate', 'sagittis', 'venenatis tristique', 'diam', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (956, 'tempus', 'volutpat', 'nam dui', 'felis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (957, 'lectus', 'neque', 'aliquam sit', 'magnis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (958, 'nulla', 'lacinia', 'molestie nibh in', 'felis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (959, 'vulputate', 'blandit', 'et commodo', 'mauris', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (960, 'consequat', 'bibendum', 'non mi', 'eu', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (961, 'imperdiet', 'luctus', 'rhoncus sed', 'eu', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (962, 'fermentum', 'justo', 'cubilia curae', 'mauris', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (963, 'amet', 'orci', 'in congue', 'id', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (964, 'neque', 'natoque', 'eget massa tempor', 'amet', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (965, 'nulla', 'sed', 'duis faucibus accumsan', 'mauris', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (966, 'blandit', 'nisi', 'auctor sed', 'urna', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (967, 'turpis', 'vel', 'nibh fusce', 'hac', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (968, 'augue', 'dui', 'vitae', 'sapien', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (969, 'sit', 'nam', 'justo lacinia eget', 'odio', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (970, 'pharetra', 'in', 'ultrices', 'dapibus', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (971, 'platea', 'pulvinar', 'suspendisse potenti cras', 'morbi', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (972, 'proin', 'mattis', 'eros viverra', 'id', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (973, 'sapien', 'ac', 'adipiscing', 'tincidunt', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (974, 'adipiscing', 'imperdiet', 'nulla', 'in', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (975, 'erat', 'tellus', 'tempus', 'odio', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (976, 'dis', 'justo', 'pellentesque', 'eu', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (977, 'ipsum', 'vulputate', 'feugiat non', 'phasellus', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (978, 'nulla', 'ligula', 'velit donec diam', 'in', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (979, 'enim', 'justo', 'vitae', 'vestibulum', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (980, 'varius', 'fusce', 'nulla', 'est', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (981, 'nam', 'scelerisque', 'morbi quis tortor', 'donec', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (982, 'mus', 'hendrerit', 'sem duis', 'sem', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (983, 'fusce', 'luctus', 'orci luctus et', 'commodo', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (984, 'placerat', 'aliquet', 'urna pretium nisl', 'justo', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (985, 'at', 'sapien', 'quis turpis sed', 'nulla', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (986, 'purus', 'primis', 'ut nulla sed', 'fermentum', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (987, 'at', 'est', 'justo', 'elementum', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (988, 'vel', 'consequat', 'vulputate', 'dis', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (989, 'rutrum', 'vitae', 'sed', 'at', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (990, 'laoreet', 'et', 'accumsan tortor quis', 'viverra', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (991, 'tristique', 'parturient', 'felis', 'odio', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (992, 'augue', 'proin', 'eu mi', 'etiam', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (993, 'cum', 'penatibus', 'in purus', 'sagittis', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (994, 'sollicitudin', 'dolor', 'vitae', 'vulputate', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (995, 'eleifend', 'sed', 'fusce posuere', 'augue', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (996, 'odio', 'convallis', 'nunc commodo placerat', 'velit', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (997, 'aliquam', 'sit', 'nulla', 'porttitor', 'A');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (998, 'lectus', 'in', 'viverra dapibus', 'enim', 'C');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (999, 'curabitur', 'nisi', 'pulvinar lobortis est', 'fusce', 'B');
insert into video (multimedia_id, tipo, codificacion, tipo_transporte, protocolo_transmision, clasificacion) values (1000, 'erat', 'congue', 'maecenas rhoncus', 'viverra', 'B');
